// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice = ImgContentSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | FormulierSlice
  | ContactformSlice
  | ImgContentSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SettingsDocumentDataSlicesSlice = FooterSlice | HeaderSlice;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Header field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  header: prismic.KeyTextField;

  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomeDocument | PageDocument | SettingsDocument;

/**
 * Item in *ShopDisplay → Default → Primary → ShopDisplay*
 */
export interface ContactformSliceDefaultPrimaryShopdisplayItem {
  /**
   * Item field in *ShopDisplay → Default → Primary → ShopDisplay*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contactform.default.primary.shopdisplay[].item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item: prismic.KeyTextField;

  /**
   * ShopImg field in *ShopDisplay → Default → Primary → ShopDisplay*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contactform.default.primary.shopdisplay[].shopimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  shopimg: prismic.ImageField<never>;

  /**
   * Description field in *ShopDisplay → Default → Primary → ShopDisplay*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Product description for modal
   * - **API ID Path**: contactform.default.primary.shopdisplay[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *ShopDisplay → Default → Primary → ShopDisplay*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Buy Now
   * - **API ID Path**: contactform.default.primary.shopdisplay[].buttontext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext: prismic.KeyTextField;
}

/**
 * Primary content in *ShopDisplay → Default → Primary*
 */
export interface ContactformSliceDefaultPrimary {
  /**
   * ShopDisplay field in *ShopDisplay → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contactform.default.primary.shopdisplay[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  shopdisplay: prismic.GroupField<
    Simplify<ContactformSliceDefaultPrimaryShopdisplayItem>
  >;
}

/**
 * Default variation for ShopDisplay Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactformSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactformSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ShopDisplay*
 */
type ContactformSliceVariation = ContactformSliceDefault;

/**
 * ShopDisplay Shared Slice
 *
 * - **API ID**: `contactform`
 * - **Description**: Contactform
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactformSlice = prismic.SharedSlice<
  "contactform",
  ContactformSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * FooterHeader field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footerheader
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footerheader: prismic.RichTextField;

  /**
   * FooterDescription field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Only 5 bullet points/new lines
   * - **API ID Path**: footer.default.primary.footerdescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footerdescription: prismic.RichTextField;

  /**
   * FooterDescription2 field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Only 5 bullet points/new lines
   * - **API ID Path**: footer.default.primary.footerdescription2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footerdescription2: prismic.RichTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Footer → FooterWithImage → Primary*
 */
export interface FooterSliceFooterimagePrimary {
  /**
   * FooterHeader field in *Footer → FooterWithImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerimage.primary.footerheader
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footerheader: prismic.KeyTextField;

  /**
   * FooterDescription field in *Footer → FooterWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Only 5 bullet points/new lines
   * - **API ID Path**: footer.footerimage.primary.footerdescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footerdescription: prismic.RichTextField;

  /**
   * FooterImage field in *Footer → FooterWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerimage.primary.footerimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  footerimage: prismic.ImageField<never>;
}

/**
 * FooterWithImage variation for Footer Slice
 *
 * - **API ID**: `footerimage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceFooterimage = prismic.SharedSliceVariation<
  "footerimage",
  Simplify<FooterSliceFooterimagePrimary>,
  never
>;

/**
 * Primary content in *Footer → FooterWithMap → Primary*
 */
export interface FooterSliceFootermapPrimary {
  /**
   * FooterHeader field in *Footer → FooterWithMap → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footermap.primary.footerheader
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footerheader: prismic.KeyTextField;

  /**
   * FooterDescription field in *Footer → FooterWithMap → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Only 5 bullet points/new lines
   * - **API ID Path**: footer.footermap.primary.footerdescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footerdescription: prismic.RichTextField;

  /**
   * FooterMap field in *Footer → FooterWithMap → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footermap.primary.footermap
   * - **Documentation**: https://prismic.io/docs/fields/geopoint
   */
  footermap: prismic.GeoPointField;
}

/**
 * FooterWithMap variation for Footer Slice
 *
 * - **API ID**: `footermap`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceFootermap = prismic.SharedSliceVariation<
  "footermap",
  Simplify<FooterSliceFootermapPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation =
  | FooterSliceDefault
  | FooterSliceFooterimage
  | FooterSliceFootermap;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Formulier → Default → Primary*
 */
export interface FormulierSliceDefaultPrimary {
  /**
   * FormHeader field in *Formulier → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact us!
   * - **API ID Path**: formulier.default.primary.formheader
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  formheader: prismic.KeyTextField;
}

/**
 * Default variation for Formulier Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormulierSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormulierSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Formulier*
 */
type FormulierSliceVariation = FormulierSliceDefault;

/**
 * Formulier Shared Slice
 *
 * - **API ID**: `formulier`
 * - **Description**: Formulier
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormulierSlice = prismic.SharedSlice<
  "formulier",
  FormulierSliceVariation
>;

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Header Title field in *Header → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.Title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  Title: prismic.RichTextField;

  /**
   * ButtonPage1 field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.buttonpage1
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonpage1: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * ButtonText1 field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.buttontext1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext1: prismic.KeyTextField;

  /**
   * ButtonPage2 field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.buttonpage2
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonpage2: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * ButtonText2 field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.buttontext2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext2: prismic.KeyTextField;

  /**
   * ButtonPage3 field in *Header → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.buttonpage3
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonpage3: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * ButtonText3 field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.buttontext3
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttontext3: prismic.KeyTextField;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *ImgContent → ImageRight → Primary*
 */
export interface ImgContentSliceDefaultPrimary {
  /**
   * Title field in *ImgContent → ImageRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: img_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ImgContent → ImageRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: img_content.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *ImgContent → ImageRight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: img_content.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *ImgContent → ImageRight → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: img_content.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image field in *ImgContent → ImageRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: img_content.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * ImageRight variation for ImgContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImgContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImgContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImgContent → ImageLeft → Primary*
 */
export interface ImgContentSliceImageLeftPrimary {
  /**
   * Title field in *ImgContent → ImageLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: img_content.imageLeft.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ImgContent → ImageLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: img_content.imageLeft.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Label field in *ImgContent → ImageLeft → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: img_content.imageLeft.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *ImgContent → ImageLeft → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: img_content.imageLeft.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image field in *ImgContent → ImageLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: img_content.imageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * ImageLeft variation for ImgContent Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImgContentSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<ImgContentSliceImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *ImgContent*
 */
type ImgContentSliceVariation =
  | ImgContentSliceDefault
  | ImgContentSliceImageLeft;

/**
 * ImgContent Shared Slice
 *
 * - **API ID**: `img_content`
 * - **Description**: ImgContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImgContentSlice = prismic.SharedSlice<
  "img_content",
  ImgContentSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactformSlice,
      ContactformSliceDefaultPrimaryShopdisplayItem,
      ContactformSliceDefaultPrimary,
      ContactformSliceVariation,
      ContactformSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceFooterimagePrimary,
      FooterSliceFootermapPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      FooterSliceFooterimage,
      FooterSliceFootermap,
      FormulierSlice,
      FormulierSliceDefaultPrimary,
      FormulierSliceVariation,
      FormulierSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      ImgContentSlice,
      ImgContentSliceDefaultPrimary,
      ImgContentSliceImageLeftPrimary,
      ImgContentSliceVariation,
      ImgContentSliceDefault,
      ImgContentSliceImageLeft,
    };
  }
}
